
# Title of your website
title: "Colorado Demography"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Population and the Econonmy"


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "The State Demography Office is the primary state agency for population and demographic information in Colorado. Its data are used by state agencies to forecast growth or decline and to plan and develop programs and community resources."


# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'https://demography.dola.colorado.gov'
baseurl: ''


gems:
  - jekyll-feed

# Compress Layout
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all


# Misc Settings
markdown: kramdown
# permalink: pretty
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']


# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md


# used in _includes/footer_scripts
google_analytics_tracking_id: "UA-76100845-1"


# Prose.io configuration
prose:
  ignore:
    - /_includes
    - /_layouts
    - /assets
    - /geojson
    - /pages/__pages-utility
    - /pages/--Test
    - _config.yml
    - _config_dev.yml
    - CNAME
    - crawl_results.log
    - .gitignore
    - .jekyll-metadata
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - robots.txt
  media:
    - 'images'
